name: Lint

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  pyright:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.0

      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pipenv

      - name: Install pipenv
        run: python3 -m pip install --upgrade pipenv wheel --break-system-packages

      - name: Install Deps from Pipfile
        run: pipenv install --system --dev

      - name: Set up pyright
        run: echo "PYRIGHT_VERSION=$(python -c 'import pyright; print(pyright.__pyright_version__)')" >> $GITHUB_ENV

      - name: Run pyright (Linux)
        uses: jakebailey/pyright-action@v1.7.0
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          python-version: ${{ matrix.python-version }}
          python-platform: Linux
          no-comments: true
          warnings: true

      - name: Run pyright (Windows)
        uses: jakebailey/pyright-action@v1.7.0
        # run anyway
        if: success() || failure()
        with:
          version: ${{ env.PYRIGHT_VERSION }}
          python-version: ${{ matrix.python-version }}
          python-platform: Windows
          no-comments: true
          warnings: true
